fix test_unique_index_checkpoint
pegasi-e/ddb pull request #24
Opened 2024-12-09 22:31 UTC by muralivemulapati

2024-12-09 22:38 UTC, jeremyosterhoudt requested changes

2024-12-09 22:38 UTC, jeremyosterhoudt commented on src/execution/operator/persistent/physical_insert.cpp
> +                if (!gstate.initialized) {
indenting does not look correct.  Please align with the code indenting

2024-12-09 23:04 UTC, muralivemulapati commented on src/execution/operator/persistent/physical_insert.cpp
> +                if (!gstate.initialized) {
fixed

2024-12-10 00:14 UTC, jeremyosterhoudt approved these changes

2024-12-10 05:22 UTC, merged